name: world_time
description: Crafted with flutter to be on time

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

# fonts:
#   - family: Schyler
#   - fonts:
#       - asset: fonts/Schyler-Regular.ttf